use_frameworks!

target 'GSMessagesCustom_Example' do
  pod 'GSMessagesCustom', :path => '../'

  target 'GSMessagesCustom_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
